### ISSUE TITLE
About Pre-training on the Wikipedia dataset

### ISSUE THREAD

**Issue by dongqian0206** [ChunyuanLI/Optimus#19]
Hi Chunyuan,

Thank you for sharing the source code.

I am wondering any reason why we need to fine-tune Optimus on the Wikipedia dataset first and then fine-tune it on another four datasets (i.e., ptb, snli, etc.) for performance evaluation. 

Pre-training Optimus directly on four datasets is also possible, though the results will definitely be worse than the reported ones. The effectiveness of Optimus should be independent of if it was pre-trained on the Wikipedia dataset. Right? Otherwise, if we want to further develop a new model, then we have to fine-tune it on the Wikipedia dataset first.

Looking forward to hearing from you.

Best,

Dong

**Comment by ChunyuanLI** [comment]
You are right that the training on Wiki is to further boost the
performance. Furthermore, we also reported linear probe results on GLUE to
compare with BERT, which require an intermediate pre-training step.

**Comment by dongqian0206** [comment]
Got it! Thanks for your reply.
