### ISSUE TITLE
when will release the pre-training codes and pre-trained models ?

### ISSUE THREAD

**Issue by bojone** [ChunyuanLI/Optimus#2]

**Comment by NonaryR** [comment]
really looking forward

**Comment by NonaryR** [comment]
@ChunyuanLI I'm seeing new addition in the master branch, that's so cool ^-^, thank you!
Can you please say where I can get these datasets? 
```
export TRAIN_FILE=../data/datasets/debug_data/train.txt
export TEST_FILE=../data/datasets/debug_data/test.txt
```
In `data/datasets` folder only mentioned wiki filtered data

**Comment by ChunyuanLI** [comment]
Thanks for your careful read. The code is not fully cleaned yet. I could provide some links for you. But be sure to use with caution.

**Comment by NonaryR** [comment]
@ChunyuanLI can't find `debug_data`, just find this [script](https://github.com/ChunyuanLI/Optimus/blob/master/code/examples/big_ae/debug_data.py)
Am I missing something?
Also, I can run `run_lm_vae_training.py ` with all new additions. But I excluded `--length_weighted_loss` argument from [here](https://github.com/ChunyuanLI/Optimus/blob/master/doc/optimus_finetune_language_models.md), since that throw a error.

**Comment by ChunyuanLI** [comment]
It does not really matter if you'd like to train a standard VAE.

However, if you'd like to modify the reconstruction loss (to have a good balance between the two terms in VAE), you may `length_weighted_loss` as an option.

I update the code to include `length_weighted_loss` as an argument.

**Comment by ChunyuanLI** [comment]
A tiny dataset is added now,  this is for me to debug:

https://textae.blob.core.windows.net/optimus/data/datasets/debug_data.zip

You may switch to use other four datasets (Penn, Yelp, Yahoo, Snli) for language modeling experiments:

https://github.com/ChunyuanLI/Optimus/blob/master/data/download_datasets.md

**Comment by NonaryR** [comment]
@ChunyuanLI sorry, but I can't run `examples/big_ae/run_latent_generation.py` script, throwing error  `OSError: file ../output/LM/Snli/768/philly_vae_snli_b1.0_d5_r00.5_ra0.25_length_weighted/checkpoint-encoder-31250 not found
`
And this is true because checkpoint from [here](https://github.com/ChunyuanLI/Optimus/blob/master/doc/optimius_for_snli.md)
includes only `training.bin` file, while script above needs an `encoder checkpoint`

But `encoder`, `decoder` and `full` checkpoints exist in `output/pretrain/philly_rr3_vc4_g8_base_vae_wikipedia_pretraining_beta_schedule_beta0.0_d1.0_ro0.5_ra0.25_32_v2/checkpoint-508523/` folder, in `pretrain` output, not in `LM`
Maybe this is mistake in documentation?
Thank for you help!

**Comment by ChunyuanLI** [comment]
I will work on releasing checkpoints with `encoder`, `decoder` and `full` for the models fine-tuned on SNLI.

Meanwhile, just as a note for myself: the code can be changed a bit to load the full model directly, because the`full` model will eventually over-write the `encoder` and `decoder` weights.

**Comment by ChunyuanLI** [comment]
The zip files are updated to contain three folders: full, encoder and decoder. Please check.

**Comment by NonaryR** [comment]
Doesn't work when I run both `Interpolation` and `Reconstruction` scripts from [here](https://github.com/ChunyuanLI/Optimus/blob/master/doc/optimius_for_snli.md)
```
Evaluating interpolation:  40%|█████████████████████████████████████████████████████████▌                                                                                      | 8/20 [00:00<00:00, 55.74it/s]
Traceback (most recent call last):
  File "examples/big_ae/run_latent_generation.py", line 487, in <module>
    main()
  File "examples/big_ae/run_latent_generation.py", line 483, in main
    result = evaluate_latent_space(args, model_vae, tokenizer_encoder, tokenizer_decoder, prefix=global_step)
  File "examples/big_ae/run_latent_generation.py", line 207, in evaluate_latent_space
    result = calc_interpolate(model_vae, eval_dataloader, encoder_tokenizer, decoder_tokenizer, args, ns=100)
  File "examples/big_ae/run_latent_generation.py", line 337, in calc_interpolate
    decoder_tokenizer = decoder_tokenizer
  File "examples/big_ae/run_latent_generation.py", line 175, in sample_sequence_conditional
    outputs = model(**inputs)  # Note: we could also use 'past' with GPT-2/Transfo-XL/XLNet (cached hidden-states)
  File "/miniconda/envs/py37/lib/python3.7/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/workspace/code/pytorch_transformers/modeling_gpt2.py", line 677, in forward
    latent_as_gpt_memory=self.latent_as_gpt_memory)
  File "/miniconda/envs/py37/lib/python3.7/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/workspace/code/pytorch_transformers/modeling_gpt2.py", line 500, in forward
    hidden_states = hidden_states.view(*output_shape)
RuntimeError: shape '[1, 1, 768]' is invalid for input of size 1536
```

**Comment by ChunyuanLI** [comment]
This might happen when you used an older version of `modeling_gpt2.py` file. Can you check it first? Let me know if it does not work.

**Comment by NonaryR** [comment]
I'm using code as-is, nothing changed

**Comment by ChunyuanLI** [comment]
Sorry to hear that. I update the instructions a bit. I pull the repo, and it works at my end. Perhaps we can find a way to work together offline. My email is lichunyuan24@gmail.com

**Comment by NonaryR** [comment]
@ChunyuanLI I pull the repo too, and the error still the same. Maybe you change your docker `docker pull chunyl/pytorch-transformers:v2` and not commit those changes?

**Comment by NonaryR** [comment]
And I want to save our conversations in public space, e.g in this GitHub repo, I think, we should provide solutions for next developers, who would like to work with this code. 
This is `the first large-scale pre-trained VAE language model`, many of NLP-researches is very attracted to VAE and you publish a paper about your cool solution -- and this is nice, but what about reproducing? This is pain across the whole field, you join a dark side too?

**Comment by NonaryR** [comment]
This is really strange, but for now, scripts are magically working.
I changed nothing, only restarted terminal.
Thank for your patience and sorry for bothering
