### ISSUE TITLE
GPT2ForLatentConnector

### ISSUE THREAD

**Issue by Bila12** [ChunyuanLI/Optimus#20]
Hello, great work there ! 

Everything is fine with the docker env, and the code works amazingly. However I would like to compute the code in my own conda environement, and it seems that the version of pytorch-transformers (1.2.0) in your requirement file doesn't have **GPT2ForLatentConnector** and **BertForLatentConnector**, and I couldn't find it in other versions. 

Could you give me the actual version that is used in your code ? Or even the source code for these classes.

Thanks a lot !
Romain

**Comment by Bila12** [comment]
Oh actually that was provided sorry ! I just shouldn't have worried about the `requirement.txt` file provided in the repository where `pytorch-transformers` version 1.2.0 is installed and use the custom model. Then run everything from the folder `code`.

**Comment by kevinfd** [comment]
Thanks Bila, this helped me solve a similar issue. In case it's helpful for anyone else (or me in the future when I inevitably forget), modifying my PYTHONPATH variable fixed the issue. (line 1 in fine-tuning script):

`export PYTHONPATH="${PYTHONPATH}:/workspace/code"`
