### ISSUE TITLE
interpolation scheme 

### ISSUE THREAD

**Issue by vseledkin** [ChunyuanLI/Optimus#5]
congratulations! indeed, controlled text generation works! 

quick experiments are very promising

**experiment 1**: purpose is to generate sentences where age of the boy is continuously increasing
and spelled by letters 

src/target: 1 - > 100
seed sentence: the boy is twelve years old.

0: 0.000000 the boy is twelve years old.
13: 0.206349 the boy is twenty years old.
24: 0.380952 the boy is forty years old.
59: 0.936508 the boy is fifty years old.

(showing only uniq samples)

**experiment 2**: controlling both increasing age and gender

src/target 1: 1 - > 100
src/target 2: man - > woman
seed sentence: the boy is twelve years old.

0: 0.000000 the boy is twelve years old.
40: 0.317460 the girl is twelve years old.
49: 0.388889 the girl is twenty years old.

(showing only uniq samples)

**experiment 3**: interpolation 

0: 0.00 the sisters are hugging while holding up goodbye to get snacks before going home.
1: 0.10 the sisters are hugging while holding up snacks next to goodbye for their dad.
2: 0.20 the sisters are hugging while holding up goodbye to shopping bags in a <unk>.
3: 0.30 the sisters are hugging while holding up a sign in front of york airlines.
4: 0.40 the girl wearing beanies stands next to a truck while celebrating <unk> together.
5: 0.50 a girl in blue shirts stands posing next to a refrigerator while holding up important <unk>.
6: 0.60 a boy in a blue shirt standing amidst all construction logos is hugging while laying down a <unk>
7: 0.70 a man in a blue shirt standing next to packaging constructions with their thumbs <unk> in a row.
8: 0.80 a man in a blue outfit standing in front of a building styled like garage vaults with <unk>
9: 0.90 a man in a blue shirt standing in front of a construction base with styled <unk> decorations
10: 1.00 a man in a blue shirt standing in front of a design center with structure painted `` funhouse ''

i like it goes from "sisters" to "man" throught "girl" and "boy" this is aslo smooth in some sence :)

just amazing !!!
not every run gives good results but it is definitely a step forward! just a question of time to get it working right. 

and here is issue/question 

I noticed you use linear interpolation scheme, but as it was pointed out by Ferenc Huszár 
here https://www.inference.vc/high-dimensional-gaussian-distributions-are-soap-bubble/ 
it makes sense to evolve interpolating trajectory along surface of a sphere.

**Comment by ChunyuanLI** [comment]
Good suggestion. I'll add a version to evolve interpolating trajectory along surface of a sphere.
