### ISSUE TITLE
Number of pretraining epochs

### ISSUE THREAD

**Issue by bo-son** [ChunyuanLI/Optimus#8]
Settings in 'train_vae_wikipedia.yaml' and 'train_vae_wikipedia_distributed.yaml' seem to differ a lot. (20 at former, 1 at latter)
How many pretraining epochs did you go over? + Which script should I refer to?

**Comment by ChunyuanLI** [comment]
To get the number reported for language modeling, we pre-trained on Wiki for 1 epoch, and then fine-tuned on the downstream dataset for 1 epoch. This has provided much better results than exiting small VAEs. Note that these number can be further improved if the model is trained longer, especially on the downstream dataset.

**Comment by bo-son** [comment]
Thanks for the reply!
